[package]
name = "ha_client"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
bincode = "1.1.4"
clap = "2.33.0"
failure = "0.1.5"
lazy_static = "1.3.0"
log = "0.4.6"
num = "0.2.0"

[dependencies.ha_animation_prefabs]
path = "../../libs/animation_prefabs"

[dependencies.ha_core]
path = "../../libs/core"

[dependencies.ha_client_shared]
path = "../../libs/client_shared"

[dependencies.ha_game]
path = "../../libs/game"
features = ["client"]

[dependencies.amethyst]
version = "0.13.0"
git = "https://github.com/mvlabat/amethyst.git"
branch = "hide-hierarchy-system-desc"
features = ["nightly", "shader-compiler"]

# Bad news: https://github.com/rust-lang/cargo/issues/1197

#[target.'cfg(target_os = "macos")'.dependencies.amethyst]
#version = "0.13.0"
#git = "https://github.com/mvlabat/amethyst.git"
#branch = "hide-hierarchy-system-desc"
#features = ["metal"]

[target.'cfg(not(target_os = "macos"))'.dependencies.amethyst]
version = "0.13.0"
git = "https://github.com/mvlabat/amethyst.git"
branch = "hide-hierarchy-system-desc"
features = ["vulkan"]

#[patch."https://github.com/amethyst/amethyst.git"]
#amethyst = { path = "../amethyst" }
