cargo-features = ["profile-overrides"]

[package]
name = "hello_amethyst"
version = "0.1.0"
authors = []
edition = "2018"

[workspace]
members = [
    "assets_packer",
]

# Bad news: https://github.com/rust-lang/cargo/issues/1197

#[target.'cfg(target_os = "macos")'.dependencies.amethyst]
#version = "0.12.0"
#features = ["metal"]

[dependencies]
failure = "0.1.5"
lazy_static = "1.3.0"
log = "0.4.6"
clap = "2.33.0"

[dependencies.amethyst]
version = "0.12.0"
features = ["nightly", "shader-compiler"]

[dependencies.ha_animation_prefabs]
path = "libs/animation_prefabs"

[dependencies.ha_core]
path = "libs/core"

[dependencies.ha_game]
path = "libs/game"

[target.'cfg(not(target_os = "macos"))'.dependencies.amethyst]
version = "0.12.0"
features = ["vulkan"]

[profile.dev.overrides."*"]
opt-level = 2

#[patch."https://github.com/amethyst/amethyst.git"]
#amethyst = { path = "../amethyst" }
