cargo-features = ["profile-overrides"]

[package]
name = "hello_amethyst"
version = "0.1.0"
authors = []
edition = "2018"

[workspace]
members = [
    "assets_packer",
]

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", rev = "7abfcfc", features = ["nightly", "vulkan"] }
directories = "1.0.2"
lazy_static = "1.3.0"
log = "0.4.6"
num = "0.2.0"
rand = "0.6.5"
ron = "0.5.1"
winit = "0.19"
shrinkwraprs = "0.2.1"

[dependencies.animation_prefabs]
path = "libs/animation_prefabs"

[profile.dev.overrides."*"]
opt-level = 2

#[patch."https://github.com/amethyst/amethyst.git"]
#amethyst = { path = "../amethyst" }
