[package]
name = "hello_amethyst"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
amethyst = { version = "0.10.0", features = ["nightly"] }
lazy_static = "1.3.0"
rand = "0.6.5"

[patch.crates-io]
amethyst = { git = "https://github.com/amethyst/amethyst.git", rev = "9590802" }