cargo-features = ["profile-overrides"]

[package]
name = "hello_amethyst"
version = "0.1.0"
authors = []
edition = "2018"

[workspace]
members = [
    "assets_packer",
]

[dependencies.animation_prefabs]
path = "libs/animation_prefabs"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git", features = ["nightly", "vulkan"] }
lazy_static = "1.3.0"
rand = "0.6.5"
winit = "0.19"
directories = "1.0.2"
ron = "0.5.1"
num = "0.2.0"

[profile.dev.overrides."*"]
opt-level = 2

[patch."https://github.com/amethyst/amethyst.git"]
amethyst = { path = "../amethyst" }
